#ifndef __MODULES_EXEC_H
#define __MODULES_EXEC_H

#include <kernel/modules/module.h>

#define MODULE_EXEC_FUNC_CHECKHEADER		0x00 + MODULE_FUNC_NUM_BUILTINS
#define MODULE_EXEC_FUNC_EXECUTE			0x01 + MODULE_FUNC_NUM_BUILTINS

#endif